dist: precise
sudo: required
language: c

addons:
  apt:
    packages:
    - libsdl1.2-dev
    - lua5.1

compiler:
    - clang
    - gcc

before_install:
  - sudo add-apt-repository ppa:anatol/tup -y
  - sudo apt-get update -q
  - sudo apt-get install tup -y

before_script:
  - cd tupconf
  - lua travisconf.lua travis.config
  
script:
  - tup variant tupconf/travis.config
  - tup --verbose
