sudo: false
language: c
addons.apt.packages:
  - fuse
before_script:
  - git clone git://github.com/gittup/tup.git
  - cd tup
  - ./bootstrap.sh
script:
  - tup variant tupconf/default.config
  - tup

