dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
    - libsdl1.2-dev
    - lua5.1
    - libfuse-dev

compiler:
    - clang
    - gcc
    
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

before_install:
  - cd $HOME
  - git clone https://github.com/gittup/tup.git
  - cd tup
  - ./bootstrap.sh
  - ./tup
  - cd $TRAVIS_BUILD_DIR

script:
  - ( cd tupconf && lua travisconf.lua travis.config )
  - $HOME/tup/tup variant tupconf/travis.config; cat build-travis/tup.config
  - $HOME/tup/tup --verbose
