dist: precise
sudo: required
language: c

addons:
  apt:
    packages:
    - libsdl1.2-dev
    - lua5.1

compiler:
    - clang
    - gcc
    
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

before_install:
  - sudo add-apt-repository ppa:anatol/tup -y
  - sudo apt-get update -q
  - sudo apt-get install tup -y

script:
  - ( cd tupconf && lua travisconf.lua travis.config )
  - tup variant tupconf/travis.config; cat build-travis/tup.config
  - tup --verbose
