dist: trusty
sudo: required
language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:anatol/tup -y
  - sudo apt-get update -q
  - sudo apt-get install tup -y
  
script:
  - tup variant tupconf/default.config
  - tup

