dist: trusty
sudo: false
language: c

addons:
  apt:
    packages:
    - libsdl1.2-dev
    - lua5.1
    - fuse

compiler:
    - clang
    - gcc
    
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

before_install:
  - git clone https://github.com/gittup/tup.git
  - cd tup
  - ./bootstrap.sh
  - alias tup=~/tup/tup

script:
  - ( cd tupconf && lua travisconf.lua travis.config )
  - tup variant tupconf/travis.config; cat build-travis/tup.config
  - tup --verbose
