dist: precise
sudo: required
language: c

addons:
  apt:
    packages:
    - libsdl1.2-dev

before_install:
  - sudo add-apt-repository ppa:anatol/tup -y
  - sudo apt-get update -q
  - sudo apt-get install tup -y
  
script:
  - tup variant tupconf/default.config
  - tup

