dist: trusty
sudo: required
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libfuse-dev
      - pkg-config
      - fuse
 
 before_install:
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
before_script:
  - git clone git://github.com/gittup/tup.git
  - cd tup
  - ./bootstrap.sh
script:
  - tup variant tupconf/default.config
  - tup

